services:
  - type: web
    name: followup-api
    env: docker
    plan: starter
    region: oregon          # adjust to your preferred region
    repo: https://github.com/ryangroblerrigour/followup-api
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY
      - key: LLM_MODEL
        value: gpt-4-turbo
